'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Caption
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UI.WIN.MAIN.Caption", GetType(Caption).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Admission.
        '''</summary>
        Public Shared ReadOnly Property Admission() As String
            Get
                Return ResourceManager.GetString("Admission", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Approval of SEP guarantee.
        '''</summary>
        Public Shared ReadOnly Property AdmissionApprovalPenjaminanSEP() As String
            Get
                Return ResourceManager.GetString("AdmissionApprovalPenjaminanSEP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registration.
        '''</summary>
        Public Shared ReadOnly Property AdmissionPendaftaran() As String
            Get
                Return ResourceManager.GetString("AdmissionPendaftaran", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poli Visite.
        '''</summary>
        Public Shared ReadOnly Property AdmissionPendaftaranKunjunganPoli() As String
            Get
                Return ResourceManager.GetString("AdmissionPendaftaranKunjunganPoli", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Room Viste.
        '''</summary>
        Public Shared ReadOnly Property AdmissionPendaftaranKunjunganRuangan() As String
            Get
                Return ResourceManager.GetString("AdmissionPendaftaranKunjunganRuangan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Re-Manufacturing (PRB).
        '''</summary>
        Public Shared ReadOnly Property AdmissionPRB() As String
            Get
                Return ResourceManager.GetString("AdmissionPRB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reference.
        '''</summary>
        Public Shared ReadOnly Property AdmissionRujukan() As String
            Get
                Return ResourceManager.GetString("AdmissionRujukan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rencana Surat Kontrol / SPRI.
        '''</summary>
        Public Shared ReadOnly Property AdmissionSKD() As String
            Get
                Return ResourceManager.GetString("AdmissionSKD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pasien Pulang.
        '''</summary>
        Public Shared ReadOnly Property AdmissionUpdateTanggalPulang() As String
            Get
                Return ResourceManager.GetString("AdmissionUpdateTanggalPulang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Column Chooser.
        '''</summary>
        Public Shared ReadOnly Property ColumnChooser() As String
            Get
                Return ResourceManager.GetString("ColumnChooser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detail Column Chooser.
        '''</summary>
        Public Shared ReadOnly Property ColumnChooserDetail() As String
            Get
                Return ResourceManager.GetString("ColumnChooserDetail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Master Column Chooser.
        '''</summary>
        Public Shared ReadOnly Property ColumnChooserMaster() As String
            Get
                Return ResourceManager.GetString("ColumnChooserMaster", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Password.
        '''</summary>
        Public Shared ReadOnly Property FileChangePassword() As String
            Get
                Return ResourceManager.GetString("FileChangePassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Public Shared ReadOnly Property FileExit() As String
            Get
                Return ResourceManager.GetString("FileExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language.
        '''</summary>
        Public Shared ReadOnly Property FileLanguage() As String
            Get
                Return ResourceManager.GetString("FileLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English.
        '''</summary>
        Public Shared ReadOnly Property FileLanguageEnglish() As String
            Get
                Return ResourceManager.GetString("FileLanguageEnglish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indonesian.
        '''</summary>
        Public Shared ReadOnly Property FileLanguageIndonesian() As String
            Get
                Return ResourceManager.GetString("FileLanguageIndonesian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to F12 - Close.
        '''</summary>
        Public Shared ReadOnly Property FormClose() As String
            Get
                Return ResourceManager.GetString("FormClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View.
        '''</summary>
        Public Shared ReadOnly Property FormListButtonView() As String
            Get
                Return ResourceManager.GetString("FormListButtonView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Information.
        '''</summary>
        Public Shared ReadOnly Property FormListGroupControlInfo() As String
            Get
                Return ResourceManager.GetString("FormListGroupControlInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to F3 - Save &amp;&amp; Close.
        '''</summary>
        Public Shared ReadOnly Property FormSaveClose() As String
            Get
                Return ResourceManager.GetString("FormSaveClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to F2 - Save &amp;&amp; New.
        '''</summary>
        Public Shared ReadOnly Property FormSaveNew() As String
            Get
                Return ResourceManager.GetString("FormSaveNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to F5 - Save &amp;&amp; Pay.
        '''</summary>
        Public Shared ReadOnly Property FormSavePayment() As String
            Get
                Return ResourceManager.GetString("FormSavePayment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inventory.
        '''</summary>
        Public Shared ReadOnly Property Inventory() As String
            Get
                Return ResourceManager.GetString("Inventory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mutation.
        '''</summary>
        Public Shared ReadOnly Property InventoryMutation() As String
            Get
                Return ResourceManager.GetString("InventoryMutation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opname.
        '''</summary>
        Public Shared ReadOnly Property InventoryOpname() As String
            Get
                Return ResourceManager.GetString("InventoryOpname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report.
        '''</summary>
        Public Shared ReadOnly Property InventoryReport() As String
            Get
                Return ResourceManager.GetString("InventoryReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Monitoring Item.
        '''</summary>
        Public Shared ReadOnly Property InventoryReportMonitoringItem() As String
            Get
                Return ResourceManager.GetString("InventoryReportMonitoringItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Purchasing.
        '''</summary>
        Public Shared ReadOnly Property Purchasing() As String
            Get
                Return ResourceManager.GetString("Purchasing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Purchase Invoice.
        '''</summary>
        Public Shared ReadOnly Property PurchasingPurchaseInvoice() As String
            Get
                Return ResourceManager.GetString("PurchasingPurchaseInvoice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Purchase Order.
        '''</summary>
        Public Shared ReadOnly Property PurchasingPurchaseOrder() As String
            Get
                Return ResourceManager.GetString("PurchasingPurchaseOrder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Purchase Return.
        '''</summary>
        Public Shared ReadOnly Property PurchasingPurchaseReturn() As String
            Get
                Return ResourceManager.GetString("PurchasingPurchaseReturn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report.
        '''</summary>
        Public Shared ReadOnly Property PurchasingReport() As String
            Get
                Return ResourceManager.GetString("PurchasingReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reference.
        '''</summary>
        Public Shared ReadOnly Property Reference() As String
            Get
                Return ResourceManager.GetString("Reference", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Regligion.
        '''</summary>
        Public Shared ReadOnly Property ReferenceAgama() As String
            Get
                Return ResourceManager.GetString("ReferenceAgama", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit Way.
        '''</summary>
        Public Shared ReadOnly Property ReferenceCaraKeluar() As String
            Get
                Return ResourceManager.GetString("ReferenceCaraKeluar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Patients.
        '''</summary>
        Public Shared ReadOnly Property ReferenceCustomer() As String
            Get
                Return ResourceManager.GetString("ReferenceCustomer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poli.
        '''</summary>
        Public Shared ReadOnly Property ReferenceDepartment() As String
            Get
                Return ResourceManager.GetString("ReferenceDepartment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diagnostic (ICD X).
        '''</summary>
        Public Shared ReadOnly Property ReferenceDiagnosa() As String
            Get
                Return ResourceManager.GetString("ReferenceDiagnosa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diagnosa PRB.
        '''</summary>
        Public Shared ReadOnly Property ReferenceDiagnosa_PRB() As String
            Get
                Return ResourceManager.GetString("ReferenceDiagnosa_PRB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Doctor.
        '''</summary>
        Public Shared ReadOnly Property ReferenceDoctor() As String
            Get
                Return ResourceManager.GetString("ReferenceDoctor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Districts/City.
        '''</summary>
        Public Shared ReadOnly Property ReferenceKabupaten() As String
            Get
                Return ResourceManager.GetString("ReferenceKabupaten", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sub-District.
        '''</summary>
        Public Shared ReadOnly Property ReferenceKecamatan() As String
            Get
                Return ResourceManager.GetString("ReferenceKecamatan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Class Care.
        '''</summary>
        Public Shared ReadOnly Property ReferenceKelasRawat() As String
            Get
                Return ResourceManager.GetString("ReferenceKelasRawat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Village Office.
        '''</summary>
        Public Shared ReadOnly Property ReferenceKelurahan() As String
            Get
                Return ResourceManager.GetString("ReferenceKelurahan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Post Home.
        '''</summary>
        Public Shared ReadOnly Property ReferencePascaPulang() As String
            Get
                Return ResourceManager.GetString("ReferencePascaPulang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guarantor.
        '''</summary>
        Public Shared ReadOnly Property ReferencePenjamin() As String
            Get
                Return ResourceManager.GetString("ReferencePenjamin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fasilitas Kesehatan.
        '''</summary>
        Public Shared ReadOnly Property ReferencePPK() As String
            Get
                Return ResourceManager.GetString("ReferencePPK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Procedure (ICD IX).
        '''</summary>
        Public Shared ReadOnly Property ReferenceProcedure() As String
            Get
                Return ResourceManager.GetString("ReferenceProcedure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Provinci.
        '''</summary>
        Public Shared ReadOnly Property ReferencePropinsi() As String
            Get
                Return ResourceManager.GetString("ReferencePropinsi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Treatment Room.
        '''</summary>
        Public Shared ReadOnly Property ReferenceRuangRawat() As String
            Get
                Return ResourceManager.GetString("ReferenceRuangRawat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spesialistik.
        '''</summary>
        Public Shared ReadOnly Property ReferenceSpesialistik() As String
            Get
                Return ResourceManager.GetString("ReferenceSpesialistik", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suku.
        '''</summary>
        Public Shared ReadOnly Property ReferenceSuku() As String
            Get
                Return ResourceManager.GetString("ReferenceSuku", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search.
        '''</summary>
        Public Shared ReadOnly Property Search() As String
            Get
                Return ResourceManager.GetString("Search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Setting.
        '''</summary>
        Public Shared ReadOnly Property Setting() As String
            Get
                Return ResourceManager.GetString("Setting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database.
        '''</summary>
        Public Shared ReadOnly Property SettingDatabase() As String
            Get
                Return ResourceManager.GetString("SettingDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup.
        '''</summary>
        Public Shared ReadOnly Property SettingDatabaseBackup() As String
            Get
                Return ResourceManager.GetString("SettingDatabaseBackup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection.
        '''</summary>
        Public Shared ReadOnly Property SettingDatabaseConnection() As String
            Get
                Return ResourceManager.GetString("SettingDatabaseConnection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User.
        '''</summary>
        Public Shared ReadOnly Property SettingDatabaseConnectionUser() As String
            Get
                Return ResourceManager.GetString("SettingDatabaseConnectionUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore.
        '''</summary>
        Public Shared ReadOnly Property SettingDatabaseRestore() As String
            Get
                Return ResourceManager.GetString("SettingDatabaseRestore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User.
        '''</summary>
        Public Shared ReadOnly Property SettingUser() As String
            Get
                Return ResourceManager.GetString("SettingUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Otority.
        '''</summary>
        Public Shared ReadOnly Property SettingUserOtority() As String
            Get
                Return ResourceManager.GetString("SettingUserOtority", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User.
        '''</summary>
        Public Shared ReadOnly Property SettingUserUser() As String
            Get
                Return ResourceManager.GetString("SettingUserUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date.
        '''</summary>
        Public Shared ReadOnly Property Tanggal() As String
            Get
                Return ResourceManager.GetString("Tanggal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RS Karisma Cimareme - Information System.
        '''</summary>
        Public Shared ReadOnly Property Title() As String
            Get
                Return ResourceManager.GetString("Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User.
        '''</summary>
        Public Shared ReadOnly Property User() As String
            Get
                Return ResourceManager.GetString("User", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version.
        '''</summary>
        Public Shared ReadOnly Property Version() As String
            Get
                Return ResourceManager.GetString("Version", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
