'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Customer
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UI.WIN.MAIN.Customer", GetType(Customer).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email.
        '''</summary>
        Public Shared ReadOnly Property EMAIL() As String
            Get
                Return ResourceManager.GetString("EMAIL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aktif?.
        '''</summary>
        Public Shared ReadOnly Property ISACTIVE() As String
            Get
                Return ResourceManager.GetString("ISACTIVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jalan.
        '''</summary>
        Public Shared ReadOnly Property JALAN() As String
            Get
                Return ResourceManager.GetString("JALAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. BPJS.
        '''</summary>
        Public Shared ReadOnly Property KARTUBPJS() As String
            Get
                Return ResourceManager.GetString("KARTUBPJS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agama.
        '''</summary>
        Public Shared ReadOnly Property KDAGAMA() As String
            Get
                Return ResourceManager.GetString("KDAGAMA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Medrec.
        '''</summary>
        Public Shared ReadOnly Property KDCUSTOMER() As String
            Get
                Return ResourceManager.GetString("KDCUSTOMER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jenis Pasien.
        '''</summary>
        Public Shared ReadOnly Property KDDAFTAR_L2() As String
            Get
                Return ResourceManager.GetString("KDDAFTAR_L2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pekerjaan.
        '''</summary>
        Public Shared ReadOnly Property KDDAFTAR_L3() As String
            Get
                Return ResourceManager.GetString("KDDAFTAR_L3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hubungan Pasien.
        '''</summary>
        Public Shared ReadOnly Property KDDAFTAR_L4() As String
            Get
                Return ResourceManager.GetString("KDDAFTAR_L4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bahasa.
        '''</summary>
        Public Shared ReadOnly Property KDDAFTAR_L5() As String
            Get
                Return ResourceManager.GetString("KDDAFTAR_L5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Golongan Darah.
        '''</summary>
        Public Shared ReadOnly Property KDGOLONGANDARAH() As String
            Get
                Return ResourceManager.GetString("KDGOLONGANDARAH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jenis Kelamin.
        '''</summary>
        Public Shared ReadOnly Property KDJENISKELAMIN() As String
            Get
                Return ResourceManager.GetString("KDJENISKELAMIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kelurahan.
        '''</summary>
        Public Shared ReadOnly Property KDKELURAHAN() As String
            Get
                Return ResourceManager.GetString("KDKELURAHAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status Hidup?.
        '''</summary>
        Public Shared ReadOnly Property KDSTATUSHIDUP() As String
            Get
                Return ResourceManager.GetString("KDSTATUSHIDUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suku.
        '''</summary>
        Public Shared ReadOnly Property KDSUKU() As String
            Get
                Return ResourceManager.GetString("KDSUKU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kecamatan.
        '''</summary>
        Public Shared ReadOnly Property KECAMATAN() As String
            Get
                Return ResourceManager.GetString("KECAMATAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kode Pos.
        '''</summary>
        Public Shared ReadOnly Property KODEPPOS() As String
            Get
                Return ResourceManager.GetString("KODEPPOS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kota/Kabupaten.
        '''</summary>
        Public Shared ReadOnly Property KOTA() As String
            Get
                Return ResourceManager.GetString("KOTA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. KTP.
        '''</summary>
        Public Shared ReadOnly Property KTP() As String
            Get
                Return ResourceManager.GetString("KTP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lain-Lain.
        '''</summary>
        Public Shared ReadOnly Property LAIN_LAIN() As String
            Get
                Return ResourceManager.GetString("LAIN-LAIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nama Pasien.
        '''</summary>
        Public Shared ReadOnly Property NAME_DISPLAY() As String
            Get
                Return ResourceManager.GetString("NAME_DISPLAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warga Negara.
        '''</summary>
        Public Shared ReadOnly Property NEGARA() As String
            Get
                Return ResourceManager.GetString("NEGARA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Tlp.
        '''</summary>
        Public Shared ReadOnly Property NOTELEPON() As String
            Get
                Return ResourceManager.GetString("NOTELEPON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Tlp WA.
        '''</summary>
        Public Shared ReadOnly Property NOTELEPON_WA() As String
            Get
                Return ResourceManager.GetString("NOTELEPON_WA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pendidikan.
        '''</summary>
        Public Shared ReadOnly Property PENDIDIKAN() As String
            Get
                Return ResourceManager.GetString("PENDIDIKAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status Perkawinan.
        '''</summary>
        Public Shared ReadOnly Property STATUSKAWIN() As String
            Get
                Return ResourceManager.GetString("STATUSKAWIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tanggal Lahir.
        '''</summary>
        Public Shared ReadOnly Property TANGGALLAHIR() As String
            Get
                Return ResourceManager.GetString("TANGGALLAHIR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tempat Lahir.
        '''</summary>
        Public Shared ReadOnly Property TEMPATLAHIR() As String
            Get
                Return ResourceManager.GetString("TEMPATLAHIR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pasien.
        '''</summary>
        Public Shared ReadOnly Property TITLE() As String
            Get
                Return ResourceManager.GetString("TITLE", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
