'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class BillingRadiologi
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UI.WIN.MAIN.BillingRadiologi", GetType(BillingRadiologi).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Billing.
        '''</summary>
        Public Shared ReadOnly Property KDBILLING_POLI() As String
            Get
                Return ResourceManager.GetString("KDBILLING_POLI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Kunjungan.
        '''</summary>
        Public Shared ReadOnly Property KDKUNJUNGAN_POLI() As String
            Get
                Return ResourceManager.GetString("KDKUNJUNGAN_POLI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Pendaftaran.
        '''</summary>
        Public Shared ReadOnly Property KDPENDAFTARAN() As String
            Get
                Return ResourceManager.GetString("KDPENDAFTARAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User.
        '''</summary>
        Public Shared ReadOnly Property KDUSER() As String
            Get
                Return ResourceManager.GetString("KDUSER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nama Pasien.
        '''</summary>
        Public Shared ReadOnly Property NAMA() As String
            Get
                Return ResourceManager.GetString("NAMA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Penjamin.
        '''</summary>
        Public Shared ReadOnly Property PENJAMIN() As String
            Get
                Return ResourceManager.GetString("PENJAMIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Rekam Medis.
        '''</summary>
        Public Shared ReadOnly Property REKAMMEDIS() As String
            Get
                Return ResourceManager.GetString("REKAMMEDIS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tanggal Input.
        '''</summary>
        Public Shared ReadOnly Property TANGGAL() As String
            Get
                Return ResourceManager.GetString("TANGGAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Billing Radiologi.
        '''</summary>
        Public Shared ReadOnly Property TITLE() As String
            Get
                Return ResourceManager.GetString("TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tujuan.
        '''</summary>
        Public Shared ReadOnly Property TUJUAN() As String
            Get
                Return ResourceManager.GetString("TUJUAN", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
