'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class CashIn
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UI.WIN.MAIN.CashIn", GetType(CashIn).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Admin.
        '''</summary>
        Public Shared ReadOnly Property ADMIN() As String
            Get
                Return ResourceManager.GetString("ADMIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Charge.
        '''</summary>
        Public Shared ReadOnly Property CHARGE_PERSEN() As String
            Get
                Return ResourceManager.GetString("CHARGE_PERSEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deposit.
        '''</summary>
        Public Shared ReadOnly Property DEPOSIT() As String
            Get
                Return ResourceManager.GetString("DEPOSIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Discount.
        '''</summary>
        Public Shared ReadOnly Property DISCOUNT_PERSEN() As String
            Get
                Return ResourceManager.GetString("DISCOUNT_PERSEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Grand Total.
        '''</summary>
        Public Shared ReadOnly Property GRANDTOTAL() As String
            Get
                Return ResourceManager.GetString("GRANDTOTAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Invoice.
        '''</summary>
        Public Shared ReadOnly Property KDCASHIN() As String
            Get
                Return ResourceManager.GetString("KDCASHIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Kunjungan.
        '''</summary>
        Public Shared ReadOnly Property KDKUNJUNGAN() As String
            Get
                Return ResourceManager.GetString("KDKUNJUNGAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipe Pembayaran.
        '''</summary>
        Public Shared ReadOnly Property KDPAYMENTYPE() As String
            Get
                Return ResourceManager.GetString("KDPAYMENTYPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No. Pendaftaran.
        '''</summary>
        Public Shared ReadOnly Property KDPENDAFTARAN() As String
            Get
                Return ResourceManager.GetString("KDPENDAFTARAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Penjamin.
        '''</summary>
        Public Shared ReadOnly Property KDPENJAMIN() As String
            Get
                Return ResourceManager.GetString("KDPENJAMIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Catatan.
        '''</summary>
        Public Shared ReadOnly Property MEMO() As String
            Get
                Return ResourceManager.GetString("MEMO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rekam Medis.
        '''</summary>
        Public Shared ReadOnly Property REKAMMEDIS() As String
            Get
                Return ResourceManager.GetString("REKAMMEDIS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pembulatan.
        '''</summary>
        Public Shared ReadOnly Property ROUND() As String
            Get
                Return ResourceManager.GetString("ROUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sub Total.
        '''</summary>
        Public Shared ReadOnly Property SUBTOTAL() As String
            Get
                Return ResourceManager.GetString("SUBTOTAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tanggal Input.
        '''</summary>
        Public Shared ReadOnly Property TANGGAL() As String
            Get
                Return ResourceManager.GetString("TANGGAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kasir.
        '''</summary>
        Public Shared ReadOnly Property TITLE() As String
            Get
                Return ResourceManager.GetString("TITLE", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
