'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="USER_DATABASE")>  _
Partial Public Class DataUserDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertSET_COMPANY(instance As SET_COMPANY)
    End Sub
  Partial Private Sub UpdateSET_COMPANY(instance As SET_COMPANY)
    End Sub
  Partial Private Sub DeleteSET_COMPANY(instance As SET_COMPANY)
    End Sub
  Partial Private Sub InsertSET_OTORITY_D(instance As SET_OTORITY_D)
    End Sub
  Partial Private Sub UpdateSET_OTORITY_D(instance As SET_OTORITY_D)
    End Sub
  Partial Private Sub DeleteSET_OTORITY_D(instance As SET_OTORITY_D)
    End Sub
  Partial Private Sub InsertSET_OTORITY_H(instance As SET_OTORITY_H)
    End Sub
  Partial Private Sub UpdateSET_OTORITY_H(instance As SET_OTORITY_H)
    End Sub
  Partial Private Sub DeleteSET_OTORITY_H(instance As SET_OTORITY_H)
    End Sub
  Partial Private Sub InsertSET_USER(instance As SET_USER)
    End Sub
  Partial Private Sub UpdateSET_USER(instance As SET_USER)
    End Sub
  Partial Private Sub DeleteSET_USER(instance As SET_USER)
    End Sub
  Partial Private Sub InsertSET_USER_D(instance As SET_USER_D)
    End Sub
  Partial Private Sub UpdateSET_USER_D(instance As SET_USER_D)
    End Sub
  Partial Private Sub DeleteSET_USER_D(instance As SET_USER_D)
    End Sub
  Partial Private Sub InsertSET_USER_KDITEM_L1(instance As SET_USER_KDITEM_L1)
    End Sub
  Partial Private Sub UpdateSET_USER_KDITEM_L1(instance As SET_USER_KDITEM_L1)
    End Sub
  Partial Private Sub DeleteSET_USER_KDITEM_L1(instance As SET_USER_KDITEM_L1)
    End Sub
  Partial Private Sub InsertSET_BPJS_KONEKSI(instance As SET_BPJS_KONEKSI)
    End Sub
  Partial Private Sub UpdateSET_BPJS_KONEKSI(instance As SET_BPJS_KONEKSI)
    End Sub
  Partial Private Sub DeleteSET_BPJS_KONEKSI(instance As SET_BPJS_KONEKSI)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.DataAccess.My.MySettings.Default.USER_DATABASEConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property SET_COMPANies() As System.Data.Linq.Table(Of SET_COMPANY)
		Get
			Return Me.GetTable(Of SET_COMPANY)
		End Get
	End Property
	
	Public ReadOnly Property SET_OTORITY_Ds() As System.Data.Linq.Table(Of SET_OTORITY_D)
		Get
			Return Me.GetTable(Of SET_OTORITY_D)
		End Get
	End Property
	
	Public ReadOnly Property SET_OTORITY_Hs() As System.Data.Linq.Table(Of SET_OTORITY_H)
		Get
			Return Me.GetTable(Of SET_OTORITY_H)
		End Get
	End Property
	
	Public ReadOnly Property SET_USERs() As System.Data.Linq.Table(Of SET_USER)
		Get
			Return Me.GetTable(Of SET_USER)
		End Get
	End Property
	
	Public ReadOnly Property SET_USER_Ds() As System.Data.Linq.Table(Of SET_USER_D)
		Get
			Return Me.GetTable(Of SET_USER_D)
		End Get
	End Property
	
	Public ReadOnly Property SET_USER_KDITEM_L1s() As System.Data.Linq.Table(Of SET_USER_KDITEM_L1)
		Get
			Return Me.GetTable(Of SET_USER_KDITEM_L1)
		End Get
	End Property
	
	Public ReadOnly Property SET_BPJS_KONEKSIs() As System.Data.Linq.Table(Of SET_BPJS_KONEKSI)
		Get
			Return Me.GetTable(Of SET_BPJS_KONEKSI)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SET_COMPANY")>  _
Partial Public Class SET_COMPANY
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _KDCOMPANY As String
	
	Private _COMPANY As String
	
	Private _ADDRESS As String
	
	Private _PHONE As String
	
	Private _NPWP As String
	
	Private _ISACTIVE As Boolean
	
	Private _SET_USERs As EntitySet(Of SET_USER)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnKDCOMPANYChanging(value As String)
    End Sub
    Partial Private Sub OnKDCOMPANYChanged()
    End Sub
    Partial Private Sub OnCOMPANYChanging(value As String)
    End Sub
    Partial Private Sub OnCOMPANYChanged()
    End Sub
    Partial Private Sub OnADDRESSChanging(value As String)
    End Sub
    Partial Private Sub OnADDRESSChanged()
    End Sub
    Partial Private Sub OnPHONEChanging(value As String)
    End Sub
    Partial Private Sub OnPHONEChanged()
    End Sub
    Partial Private Sub OnNPWPChanging(value As String)
    End Sub
    Partial Private Sub OnNPWPChanged()
    End Sub
    Partial Private Sub OnISACTIVEChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISACTIVEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._SET_USERs = New EntitySet(Of SET_USER)(AddressOf Me.attach_SET_USERs, AddressOf Me.detach_SET_USERs)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDCOMPANY", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property KDCOMPANY() As String
		Get
			Return Me._KDCOMPANY
		End Get
		Set
			If (String.Equals(Me._KDCOMPANY, value) = false) Then
				Me.OnKDCOMPANYChanging(value)
				Me.SendPropertyChanging
				Me._KDCOMPANY = value
				Me.SendPropertyChanged("KDCOMPANY")
				Me.OnKDCOMPANYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COMPANY", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property COMPANY() As String
		Get
			Return Me._COMPANY
		End Get
		Set
			If (String.Equals(Me._COMPANY, value) = false) Then
				Me.OnCOMPANYChanging(value)
				Me.SendPropertyChanging
				Me._COMPANY = value
				Me.SendPropertyChanged("COMPANY")
				Me.OnCOMPANYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ADDRESS", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property ADDRESS() As String
		Get
			Return Me._ADDRESS
		End Get
		Set
			If (String.Equals(Me._ADDRESS, value) = false) Then
				Me.OnADDRESSChanging(value)
				Me.SendPropertyChanging
				Me._ADDRESS = value
				Me.SendPropertyChanged("ADDRESS")
				Me.OnADDRESSChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PHONE", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property PHONE() As String
		Get
			Return Me._PHONE
		End Get
		Set
			If (String.Equals(Me._PHONE, value) = false) Then
				Me.OnPHONEChanging(value)
				Me.SendPropertyChanging
				Me._PHONE = value
				Me.SendPropertyChanged("PHONE")
				Me.OnPHONEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NPWP", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property NPWP() As String
		Get
			Return Me._NPWP
		End Get
		Set
			If (String.Equals(Me._NPWP, value) = false) Then
				Me.OnNPWPChanging(value)
				Me.SendPropertyChanging
				Me._NPWP = value
				Me.SendPropertyChanged("NPWP")
				Me.OnNPWPChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISACTIVE", DbType:="Bit NOT NULL")>  _
	Public Property ISACTIVE() As Boolean
		Get
			Return Me._ISACTIVE
		End Get
		Set
			If ((Me._ISACTIVE = value)  _
						= false) Then
				Me.OnISACTIVEChanging(value)
				Me.SendPropertyChanging
				Me._ISACTIVE = value
				Me.SendPropertyChanged("ISACTIVE")
				Me.OnISACTIVEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SET_COMPANY_SET_USER", Storage:="_SET_USERs", ThisKey:="KDCOMPANY", OtherKey:="KDCOMPANY")>  _
	Public Property SET_USERs() As EntitySet(Of SET_USER)
		Get
			Return Me._SET_USERs
		End Get
		Set
			Me._SET_USERs.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_SET_USERs(ByVal entity As SET_USER)
		Me.SendPropertyChanging
		entity.SET_COMPANY = Me
	End Sub
	
	Private Sub detach_SET_USERs(ByVal entity As SET_USER)
		Me.SendPropertyChanging
		entity.SET_COMPANY = Nothing
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SET_OTORITY_D")>  _
Partial Public Class SET_OTORITY_D
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _KDOTORITY As String
	
	Private _MODUL As String
	
	Private _MENUNAME As String
	
	Private _ISADD As Boolean
	
	Private _ISUPDATE As Boolean
	
	Private _ISDELETE As Boolean
	
	Private _ISPRINT As Boolean
	
	Private _ISVIEW As Boolean
	
	Private _SET_OTORITY_H As EntityRef(Of SET_OTORITY_H)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnKDOTORITYChanging(value As String)
    End Sub
    Partial Private Sub OnKDOTORITYChanged()
    End Sub
    Partial Private Sub OnMODULChanging(value As String)
    End Sub
    Partial Private Sub OnMODULChanged()
    End Sub
    Partial Private Sub OnMENUNAMEChanging(value As String)
    End Sub
    Partial Private Sub OnMENUNAMEChanged()
    End Sub
    Partial Private Sub OnISADDChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISADDChanged()
    End Sub
    Partial Private Sub OnISUPDATEChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISUPDATEChanged()
    End Sub
    Partial Private Sub OnISDELETEChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISDELETEChanged()
    End Sub
    Partial Private Sub OnISPRINTChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISPRINTChanged()
    End Sub
    Partial Private Sub OnISVIEWChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISVIEWChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._SET_OTORITY_H = CType(Nothing, EntityRef(Of SET_OTORITY_H))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDOTORITY", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property KDOTORITY() As String
		Get
			Return Me._KDOTORITY
		End Get
		Set
			If (String.Equals(Me._KDOTORITY, value) = false) Then
				If Me._SET_OTORITY_H.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnKDOTORITYChanging(value)
				Me.SendPropertyChanging
				Me._KDOTORITY = value
				Me.SendPropertyChanged("KDOTORITY")
				Me.OnKDOTORITYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MODUL", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property MODUL() As String
		Get
			Return Me._MODUL
		End Get
		Set
			If (String.Equals(Me._MODUL, value) = false) Then
				Me.OnMODULChanging(value)
				Me.SendPropertyChanging
				Me._MODUL = value
				Me.SendPropertyChanged("MODUL")
				Me.OnMODULChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MENUNAME", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property MENUNAME() As String
		Get
			Return Me._MENUNAME
		End Get
		Set
			If (String.Equals(Me._MENUNAME, value) = false) Then
				Me.OnMENUNAMEChanging(value)
				Me.SendPropertyChanging
				Me._MENUNAME = value
				Me.SendPropertyChanged("MENUNAME")
				Me.OnMENUNAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISADD", DbType:="Bit NOT NULL")>  _
	Public Property ISADD() As Boolean
		Get
			Return Me._ISADD
		End Get
		Set
			If ((Me._ISADD = value)  _
						= false) Then
				Me.OnISADDChanging(value)
				Me.SendPropertyChanging
				Me._ISADD = value
				Me.SendPropertyChanged("ISADD")
				Me.OnISADDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISUPDATE", DbType:="Bit NOT NULL")>  _
	Public Property ISUPDATE() As Boolean
		Get
			Return Me._ISUPDATE
		End Get
		Set
			If ((Me._ISUPDATE = value)  _
						= false) Then
				Me.OnISUPDATEChanging(value)
				Me.SendPropertyChanging
				Me._ISUPDATE = value
				Me.SendPropertyChanged("ISUPDATE")
				Me.OnISUPDATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISDELETE", DbType:="Bit NOT NULL")>  _
	Public Property ISDELETE() As Boolean
		Get
			Return Me._ISDELETE
		End Get
		Set
			If ((Me._ISDELETE = value)  _
						= false) Then
				Me.OnISDELETEChanging(value)
				Me.SendPropertyChanging
				Me._ISDELETE = value
				Me.SendPropertyChanged("ISDELETE")
				Me.OnISDELETEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISPRINT", DbType:="Bit NOT NULL")>  _
	Public Property ISPRINT() As Boolean
		Get
			Return Me._ISPRINT
		End Get
		Set
			If ((Me._ISPRINT = value)  _
						= false) Then
				Me.OnISPRINTChanging(value)
				Me.SendPropertyChanging
				Me._ISPRINT = value
				Me.SendPropertyChanged("ISPRINT")
				Me.OnISPRINTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISVIEW", DbType:="Bit NOT NULL")>  _
	Public Property ISVIEW() As Boolean
		Get
			Return Me._ISVIEW
		End Get
		Set
			If ((Me._ISVIEW = value)  _
						= false) Then
				Me.OnISVIEWChanging(value)
				Me.SendPropertyChanging
				Me._ISVIEW = value
				Me.SendPropertyChanged("ISVIEW")
				Me.OnISVIEWChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SET_OTORITY_H_SET_OTORITY_D", Storage:="_SET_OTORITY_H", ThisKey:="KDOTORITY", OtherKey:="KDOTORITY", IsForeignKey:=true)>  _
	Public Property SET_OTORITY_H() As SET_OTORITY_H
		Get
			Return Me._SET_OTORITY_H.Entity
		End Get
		Set
			Dim previousValue As SET_OTORITY_H = Me._SET_OTORITY_H.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._SET_OTORITY_H.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._SET_OTORITY_H.Entity = Nothing
					previousValue.SET_OTORITY_Ds.Remove(Me)
				End If
				Me._SET_OTORITY_H.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.SET_OTORITY_Ds.Add(Me)
					Me._KDOTORITY = value.KDOTORITY
				Else
					Me._KDOTORITY = CType(Nothing, String)
				End If
				Me.SendPropertyChanged("SET_OTORITY_H")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SET_OTORITY_H")>  _
Partial Public Class SET_OTORITY_H
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _KDOTORITY As String
	
	Private _DESCRIPTION As String
	
	Private _ISACTIVE As Boolean
	
	Private _SET_OTORITY_Ds As EntitySet(Of SET_OTORITY_D)
	
	Private _SET_USERs As EntitySet(Of SET_USER)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnKDOTORITYChanging(value As String)
    End Sub
    Partial Private Sub OnKDOTORITYChanged()
    End Sub
    Partial Private Sub OnDESCRIPTIONChanging(value As String)
    End Sub
    Partial Private Sub OnDESCRIPTIONChanged()
    End Sub
    Partial Private Sub OnISACTIVEChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISACTIVEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._SET_OTORITY_Ds = New EntitySet(Of SET_OTORITY_D)(AddressOf Me.attach_SET_OTORITY_Ds, AddressOf Me.detach_SET_OTORITY_Ds)
		Me._SET_USERs = New EntitySet(Of SET_USER)(AddressOf Me.attach_SET_USERs, AddressOf Me.detach_SET_USERs)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDOTORITY", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property KDOTORITY() As String
		Get
			Return Me._KDOTORITY
		End Get
		Set
			If (String.Equals(Me._KDOTORITY, value) = false) Then
				Me.OnKDOTORITYChanging(value)
				Me.SendPropertyChanging
				Me._KDOTORITY = value
				Me.SendPropertyChanged("KDOTORITY")
				Me.OnKDOTORITYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DESCRIPTION", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property DESCRIPTION() As String
		Get
			Return Me._DESCRIPTION
		End Get
		Set
			If (String.Equals(Me._DESCRIPTION, value) = false) Then
				Me.OnDESCRIPTIONChanging(value)
				Me.SendPropertyChanging
				Me._DESCRIPTION = value
				Me.SendPropertyChanged("DESCRIPTION")
				Me.OnDESCRIPTIONChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISACTIVE", DbType:="Bit NOT NULL")>  _
	Public Property ISACTIVE() As Boolean
		Get
			Return Me._ISACTIVE
		End Get
		Set
			If ((Me._ISACTIVE = value)  _
						= false) Then
				Me.OnISACTIVEChanging(value)
				Me.SendPropertyChanging
				Me._ISACTIVE = value
				Me.SendPropertyChanged("ISACTIVE")
				Me.OnISACTIVEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SET_OTORITY_H_SET_OTORITY_D", Storage:="_SET_OTORITY_Ds", ThisKey:="KDOTORITY", OtherKey:="KDOTORITY")>  _
	Public Property SET_OTORITY_Ds() As EntitySet(Of SET_OTORITY_D)
		Get
			Return Me._SET_OTORITY_Ds
		End Get
		Set
			Me._SET_OTORITY_Ds.Assign(value)
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SET_OTORITY_H_SET_USER", Storage:="_SET_USERs", ThisKey:="KDOTORITY", OtherKey:="KDOTORITY")>  _
	Public Property SET_USERs() As EntitySet(Of SET_USER)
		Get
			Return Me._SET_USERs
		End Get
		Set
			Me._SET_USERs.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_SET_OTORITY_Ds(ByVal entity As SET_OTORITY_D)
		Me.SendPropertyChanging
		entity.SET_OTORITY_H = Me
	End Sub
	
	Private Sub detach_SET_OTORITY_Ds(ByVal entity As SET_OTORITY_D)
		Me.SendPropertyChanging
		entity.SET_OTORITY_H = Nothing
	End Sub
	
	Private Sub attach_SET_USERs(ByVal entity As SET_USER)
		Me.SendPropertyChanging
		entity.SET_OTORITY_H = Me
	End Sub
	
	Private Sub detach_SET_USERs(ByVal entity As SET_USER)
		Me.SendPropertyChanging
		entity.SET_OTORITY_H = Nothing
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SET_USER")>  _
Partial Public Class SET_USER
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _KDUSER As String
	
	Private _KDSERVER As String
	
	Private _KDDATABASE As String
	
	Private _KDSERVER_TAX As String
	
	Private _KDDATABASE_TAX As String
	
	Private _KDOTORITY As String
	
	Private _KDCOMPANY As String
	
	Private _PASSWORD As String
	
	Private _ISACTIVE As Boolean
	
	Private _NIK As String
	
	Private _SET_USER_Ds As EntitySet(Of SET_USER_D)
	
	Private _SET_COMPANY As EntityRef(Of SET_COMPANY)
	
	Private _SET_OTORITY_H As EntityRef(Of SET_OTORITY_H)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnKDUSERChanging(value As String)
    End Sub
    Partial Private Sub OnKDUSERChanged()
    End Sub
    Partial Private Sub OnKDSERVERChanging(value As String)
    End Sub
    Partial Private Sub OnKDSERVERChanged()
    End Sub
    Partial Private Sub OnKDDATABASEChanging(value As String)
    End Sub
    Partial Private Sub OnKDDATABASEChanged()
    End Sub
    Partial Private Sub OnKDSERVER_TAXChanging(value As String)
    End Sub
    Partial Private Sub OnKDSERVER_TAXChanged()
    End Sub
    Partial Private Sub OnKDDATABASE_TAXChanging(value As String)
    End Sub
    Partial Private Sub OnKDDATABASE_TAXChanged()
    End Sub
    Partial Private Sub OnKDOTORITYChanging(value As String)
    End Sub
    Partial Private Sub OnKDOTORITYChanged()
    End Sub
    Partial Private Sub OnKDCOMPANYChanging(value As String)
    End Sub
    Partial Private Sub OnKDCOMPANYChanged()
    End Sub
    Partial Private Sub OnPASSWORDChanging(value As String)
    End Sub
    Partial Private Sub OnPASSWORDChanged()
    End Sub
    Partial Private Sub OnISACTIVEChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISACTIVEChanged()
    End Sub
    Partial Private Sub OnNIKChanging(value As String)
    End Sub
    Partial Private Sub OnNIKChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._SET_USER_Ds = New EntitySet(Of SET_USER_D)(AddressOf Me.attach_SET_USER_Ds, AddressOf Me.detach_SET_USER_Ds)
		Me._SET_COMPANY = CType(Nothing, EntityRef(Of SET_COMPANY))
		Me._SET_OTORITY_H = CType(Nothing, EntityRef(Of SET_OTORITY_H))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDUSER", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property KDUSER() As String
		Get
			Return Me._KDUSER
		End Get
		Set
			If (String.Equals(Me._KDUSER, value) = false) Then
				Me.OnKDUSERChanging(value)
				Me.SendPropertyChanging
				Me._KDUSER = value
				Me.SendPropertyChanged("KDUSER")
				Me.OnKDUSERChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDSERVER", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property KDSERVER() As String
		Get
			Return Me._KDSERVER
		End Get
		Set
			If (String.Equals(Me._KDSERVER, value) = false) Then
				Me.OnKDSERVERChanging(value)
				Me.SendPropertyChanging
				Me._KDSERVER = value
				Me.SendPropertyChanged("KDSERVER")
				Me.OnKDSERVERChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDDATABASE", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property KDDATABASE() As String
		Get
			Return Me._KDDATABASE
		End Get
		Set
			If (String.Equals(Me._KDDATABASE, value) = false) Then
				Me.OnKDDATABASEChanging(value)
				Me.SendPropertyChanging
				Me._KDDATABASE = value
				Me.SendPropertyChanged("KDDATABASE")
				Me.OnKDDATABASEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDSERVER_TAX", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property KDSERVER_TAX() As String
		Get
			Return Me._KDSERVER_TAX
		End Get
		Set
			If (String.Equals(Me._KDSERVER_TAX, value) = false) Then
				Me.OnKDSERVER_TAXChanging(value)
				Me.SendPropertyChanging
				Me._KDSERVER_TAX = value
				Me.SendPropertyChanged("KDSERVER_TAX")
				Me.OnKDSERVER_TAXChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDDATABASE_TAX", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property KDDATABASE_TAX() As String
		Get
			Return Me._KDDATABASE_TAX
		End Get
		Set
			If (String.Equals(Me._KDDATABASE_TAX, value) = false) Then
				Me.OnKDDATABASE_TAXChanging(value)
				Me.SendPropertyChanging
				Me._KDDATABASE_TAX = value
				Me.SendPropertyChanged("KDDATABASE_TAX")
				Me.OnKDDATABASE_TAXChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDOTORITY", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property KDOTORITY() As String
		Get
			Return Me._KDOTORITY
		End Get
		Set
			If (String.Equals(Me._KDOTORITY, value) = false) Then
				If Me._SET_OTORITY_H.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnKDOTORITYChanging(value)
				Me.SendPropertyChanging
				Me._KDOTORITY = value
				Me.SendPropertyChanged("KDOTORITY")
				Me.OnKDOTORITYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDCOMPANY", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property KDCOMPANY() As String
		Get
			Return Me._KDCOMPANY
		End Get
		Set
			If (String.Equals(Me._KDCOMPANY, value) = false) Then
				If Me._SET_COMPANY.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnKDCOMPANYChanging(value)
				Me.SendPropertyChanging
				Me._KDCOMPANY = value
				Me.SendPropertyChanged("KDCOMPANY")
				Me.OnKDCOMPANYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PASSWORD", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property PASSWORD() As String
		Get
			Return Me._PASSWORD
		End Get
		Set
			If (String.Equals(Me._PASSWORD, value) = false) Then
				Me.OnPASSWORDChanging(value)
				Me.SendPropertyChanging
				Me._PASSWORD = value
				Me.SendPropertyChanged("PASSWORD")
				Me.OnPASSWORDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISACTIVE", DbType:="Bit NOT NULL")>  _
	Public Property ISACTIVE() As Boolean
		Get
			Return Me._ISACTIVE
		End Get
		Set
			If ((Me._ISACTIVE = value)  _
						= false) Then
				Me.OnISACTIVEChanging(value)
				Me.SendPropertyChanging
				Me._ISACTIVE = value
				Me.SendPropertyChanged("ISACTIVE")
				Me.OnISACTIVEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NIK", DbType:="NVarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property NIK() As String
		Get
			Return Me._NIK
		End Get
		Set
			If (String.Equals(Me._NIK, value) = false) Then
				Me.OnNIKChanging(value)
				Me.SendPropertyChanging
				Me._NIK = value
				Me.SendPropertyChanged("NIK")
				Me.OnNIKChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SET_USER_SET_USER_D", Storage:="_SET_USER_Ds", ThisKey:="KDUSER", OtherKey:="KDUSER")>  _
	Public Property SET_USER_Ds() As EntitySet(Of SET_USER_D)
		Get
			Return Me._SET_USER_Ds
		End Get
		Set
			Me._SET_USER_Ds.Assign(value)
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SET_COMPANY_SET_USER", Storage:="_SET_COMPANY", ThisKey:="KDCOMPANY", OtherKey:="KDCOMPANY", IsForeignKey:=true)>  _
	Public Property SET_COMPANY() As SET_COMPANY
		Get
			Return Me._SET_COMPANY.Entity
		End Get
		Set
			Dim previousValue As SET_COMPANY = Me._SET_COMPANY.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._SET_COMPANY.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._SET_COMPANY.Entity = Nothing
					previousValue.SET_USERs.Remove(Me)
				End If
				Me._SET_COMPANY.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.SET_USERs.Add(Me)
					Me._KDCOMPANY = value.KDCOMPANY
				Else
					Me._KDCOMPANY = CType(Nothing, String)
				End If
				Me.SendPropertyChanged("SET_COMPANY")
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SET_OTORITY_H_SET_USER", Storage:="_SET_OTORITY_H", ThisKey:="KDOTORITY", OtherKey:="KDOTORITY", IsForeignKey:=true)>  _
	Public Property SET_OTORITY_H() As SET_OTORITY_H
		Get
			Return Me._SET_OTORITY_H.Entity
		End Get
		Set
			Dim previousValue As SET_OTORITY_H = Me._SET_OTORITY_H.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._SET_OTORITY_H.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._SET_OTORITY_H.Entity = Nothing
					previousValue.SET_USERs.Remove(Me)
				End If
				Me._SET_OTORITY_H.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.SET_USERs.Add(Me)
					Me._KDOTORITY = value.KDOTORITY
				Else
					Me._KDOTORITY = CType(Nothing, String)
				End If
				Me.SendPropertyChanged("SET_OTORITY_H")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_SET_USER_Ds(ByVal entity As SET_USER_D)
		Me.SendPropertyChanging
		entity.SET_USER = Me
	End Sub
	
	Private Sub detach_SET_USER_Ds(ByVal entity As SET_USER_D)
		Me.SendPropertyChanging
		entity.SET_USER = Nothing
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SET_USER_D")>  _
Partial Public Class SET_USER_D
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _KDUSER As String
	
	Private _SEQ As Integer
	
	Private _KDWAREHOUSE As String
	
	Private _ISDEFAULT As Boolean
	
	Private _REMARKS As String
	
	Private _SET_USER As EntityRef(Of SET_USER)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnKDUSERChanging(value As String)
    End Sub
    Partial Private Sub OnKDUSERChanged()
    End Sub
    Partial Private Sub OnSEQChanging(value As Integer)
    End Sub
    Partial Private Sub OnSEQChanged()
    End Sub
    Partial Private Sub OnKDWAREHOUSEChanging(value As String)
    End Sub
    Partial Private Sub OnKDWAREHOUSEChanged()
    End Sub
    Partial Private Sub OnISDEFAULTChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISDEFAULTChanged()
    End Sub
    Partial Private Sub OnREMARKSChanging(value As String)
    End Sub
    Partial Private Sub OnREMARKSChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._SET_USER = CType(Nothing, EntityRef(Of SET_USER))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDUSER", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property KDUSER() As String
		Get
			Return Me._KDUSER
		End Get
		Set
			If (String.Equals(Me._KDUSER, value) = false) Then
				If Me._SET_USER.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnKDUSERChanging(value)
				Me.SendPropertyChanging
				Me._KDUSER = value
				Me.SendPropertyChanged("KDUSER")
				Me.OnKDUSERChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SEQ", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property SEQ() As Integer
		Get
			Return Me._SEQ
		End Get
		Set
			If ((Me._SEQ = value)  _
						= false) Then
				Me.OnSEQChanging(value)
				Me.SendPropertyChanging
				Me._SEQ = value
				Me.SendPropertyChanged("SEQ")
				Me.OnSEQChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDWAREHOUSE", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property KDWAREHOUSE() As String
		Get
			Return Me._KDWAREHOUSE
		End Get
		Set
			If (String.Equals(Me._KDWAREHOUSE, value) = false) Then
				Me.OnKDWAREHOUSEChanging(value)
				Me.SendPropertyChanging
				Me._KDWAREHOUSE = value
				Me.SendPropertyChanged("KDWAREHOUSE")
				Me.OnKDWAREHOUSEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISDEFAULT", DbType:="Bit NOT NULL")>  _
	Public Property ISDEFAULT() As Boolean
		Get
			Return Me._ISDEFAULT
		End Get
		Set
			If ((Me._ISDEFAULT = value)  _
						= false) Then
				Me.OnISDEFAULTChanging(value)
				Me.SendPropertyChanging
				Me._ISDEFAULT = value
				Me.SendPropertyChanged("ISDEFAULT")
				Me.OnISDEFAULTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_REMARKS", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property REMARKS() As String
		Get
			Return Me._REMARKS
		End Get
		Set
			If (String.Equals(Me._REMARKS, value) = false) Then
				Me.OnREMARKSChanging(value)
				Me.SendPropertyChanging
				Me._REMARKS = value
				Me.SendPropertyChanged("REMARKS")
				Me.OnREMARKSChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SET_USER_SET_USER_D", Storage:="_SET_USER", ThisKey:="KDUSER", OtherKey:="KDUSER", IsForeignKey:=true)>  _
	Public Property SET_USER() As SET_USER
		Get
			Return Me._SET_USER.Entity
		End Get
		Set
			Dim previousValue As SET_USER = Me._SET_USER.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._SET_USER.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._SET_USER.Entity = Nothing
					previousValue.SET_USER_Ds.Remove(Me)
				End If
				Me._SET_USER.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.SET_USER_Ds.Add(Me)
					Me._KDUSER = value.KDUSER
				Else
					Me._KDUSER = CType(Nothing, String)
				End If
				Me.SendPropertyChanged("SET_USER")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SET_USER_KDITEM_L1")>  _
Partial Public Class SET_USER_KDITEM_L1
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _KDUSER As String
	
	Private _SEQ As Integer
	
	Private _KDITEM_L1 As String
	
	Private _ISDEFAULT As Boolean
	
	Private _REMARKS As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnKDUSERChanging(value As String)
    End Sub
    Partial Private Sub OnKDUSERChanged()
    End Sub
    Partial Private Sub OnSEQChanging(value As Integer)
    End Sub
    Partial Private Sub OnSEQChanged()
    End Sub
    Partial Private Sub OnKDITEM_L1Changing(value As String)
    End Sub
    Partial Private Sub OnKDITEM_L1Changed()
    End Sub
    Partial Private Sub OnISDEFAULTChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISDEFAULTChanged()
    End Sub
    Partial Private Sub OnREMARKSChanging(value As String)
    End Sub
    Partial Private Sub OnREMARKSChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDUSER", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property KDUSER() As String
		Get
			Return Me._KDUSER
		End Get
		Set
			If (String.Equals(Me._KDUSER, value) = false) Then
				Me.OnKDUSERChanging(value)
				Me.SendPropertyChanging
				Me._KDUSER = value
				Me.SendPropertyChanged("KDUSER")
				Me.OnKDUSERChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SEQ", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property SEQ() As Integer
		Get
			Return Me._SEQ
		End Get
		Set
			If ((Me._SEQ = value)  _
						= false) Then
				Me.OnSEQChanging(value)
				Me.SendPropertyChanging
				Me._SEQ = value
				Me.SendPropertyChanged("SEQ")
				Me.OnSEQChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDITEM_L1", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property KDITEM_L1() As String
		Get
			Return Me._KDITEM_L1
		End Get
		Set
			If (String.Equals(Me._KDITEM_L1, value) = false) Then
				Me.OnKDITEM_L1Changing(value)
				Me.SendPropertyChanging
				Me._KDITEM_L1 = value
				Me.SendPropertyChanged("KDITEM_L1")
				Me.OnKDITEM_L1Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISDEFAULT", DbType:="Bit NOT NULL")>  _
	Public Property ISDEFAULT() As Boolean
		Get
			Return Me._ISDEFAULT
		End Get
		Set
			If ((Me._ISDEFAULT = value)  _
						= false) Then
				Me.OnISDEFAULTChanging(value)
				Me.SendPropertyChanging
				Me._ISDEFAULT = value
				Me.SendPropertyChanged("ISDEFAULT")
				Me.OnISDEFAULTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_REMARKS", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property REMARKS() As String
		Get
			Return Me._REMARKS
		End Get
		Set
			If (String.Equals(Me._REMARKS, value) = false) Then
				Me.OnREMARKSChanging(value)
				Me.SendPropertyChanging
				Me._REMARKS = value
				Me.SendPropertyChanged("REMARKS")
				Me.OnREMARKSChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SET_BPJS_KONEKSI")>  _
Partial Public Class SET_BPJS_KONEKSI
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _DATECREATED As Date
	
	Private _DATEUPDATED As Date
	
	Private _KDKONEKSI As String
	
	Private _NAME_DISPLAY As String
	
	Private _PPKPELAYANAN As String
	
	Private _CONSID As String
	
	Private _SECREATKEY As String
	
	Private _ALAMATWEB As String
	
	Private _REMARKS As String
	
	Private _ISACTIVE As Boolean
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnDATECREATEDChanging(value As Date)
    End Sub
    Partial Private Sub OnDATECREATEDChanged()
    End Sub
    Partial Private Sub OnDATEUPDATEDChanging(value As Date)
    End Sub
    Partial Private Sub OnDATEUPDATEDChanged()
    End Sub
    Partial Private Sub OnKDKONEKSIChanging(value As String)
    End Sub
    Partial Private Sub OnKDKONEKSIChanged()
    End Sub
    Partial Private Sub OnNAME_DISPLAYChanging(value As String)
    End Sub
    Partial Private Sub OnNAME_DISPLAYChanged()
    End Sub
    Partial Private Sub OnPPKPELAYANANChanging(value As String)
    End Sub
    Partial Private Sub OnPPKPELAYANANChanged()
    End Sub
    Partial Private Sub OnCONSIDChanging(value As String)
    End Sub
    Partial Private Sub OnCONSIDChanged()
    End Sub
    Partial Private Sub OnSECREATKEYChanging(value As String)
    End Sub
    Partial Private Sub OnSECREATKEYChanged()
    End Sub
    Partial Private Sub OnALAMATWEBChanging(value As String)
    End Sub
    Partial Private Sub OnALAMATWEBChanged()
    End Sub
    Partial Private Sub OnREMARKSChanging(value As String)
    End Sub
    Partial Private Sub OnREMARKSChanged()
    End Sub
    Partial Private Sub OnISACTIVEChanging(value As Boolean)
    End Sub
    Partial Private Sub OnISACTIVEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DATECREATED", DbType:="SmallDateTime NOT NULL")>  _
	Public Property DATECREATED() As Date
		Get
			Return Me._DATECREATED
		End Get
		Set
			If ((Me._DATECREATED = value)  _
						= false) Then
				Me.OnDATECREATEDChanging(value)
				Me.SendPropertyChanging
				Me._DATECREATED = value
				Me.SendPropertyChanged("DATECREATED")
				Me.OnDATECREATEDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DATEUPDATED", DbType:="SmallDateTime NOT NULL")>  _
	Public Property DATEUPDATED() As Date
		Get
			Return Me._DATEUPDATED
		End Get
		Set
			If ((Me._DATEUPDATED = value)  _
						= false) Then
				Me.OnDATEUPDATEDChanging(value)
				Me.SendPropertyChanging
				Me._DATEUPDATED = value
				Me.SendPropertyChanged("DATEUPDATED")
				Me.OnDATEUPDATEDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KDKONEKSI", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property KDKONEKSI() As String
		Get
			Return Me._KDKONEKSI
		End Get
		Set
			If (String.Equals(Me._KDKONEKSI, value) = false) Then
				Me.OnKDKONEKSIChanging(value)
				Me.SendPropertyChanging
				Me._KDKONEKSI = value
				Me.SendPropertyChanged("KDKONEKSI")
				Me.OnKDKONEKSIChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NAME_DISPLAY", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property NAME_DISPLAY() As String
		Get
			Return Me._NAME_DISPLAY
		End Get
		Set
			If (String.Equals(Me._NAME_DISPLAY, value) = false) Then
				Me.OnNAME_DISPLAYChanging(value)
				Me.SendPropertyChanging
				Me._NAME_DISPLAY = value
				Me.SendPropertyChanged("NAME_DISPLAY")
				Me.OnNAME_DISPLAYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PPKPELAYANAN", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property PPKPELAYANAN() As String
		Get
			Return Me._PPKPELAYANAN
		End Get
		Set
			If (String.Equals(Me._PPKPELAYANAN, value) = false) Then
				Me.OnPPKPELAYANANChanging(value)
				Me.SendPropertyChanging
				Me._PPKPELAYANAN = value
				Me.SendPropertyChanged("PPKPELAYANAN")
				Me.OnPPKPELAYANANChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CONSID", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property CONSID() As String
		Get
			Return Me._CONSID
		End Get
		Set
			If (String.Equals(Me._CONSID, value) = false) Then
				Me.OnCONSIDChanging(value)
				Me.SendPropertyChanging
				Me._CONSID = value
				Me.SendPropertyChanged("CONSID")
				Me.OnCONSIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SECREATKEY", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property SECREATKEY() As String
		Get
			Return Me._SECREATKEY
		End Get
		Set
			If (String.Equals(Me._SECREATKEY, value) = false) Then
				Me.OnSECREATKEYChanging(value)
				Me.SendPropertyChanging
				Me._SECREATKEY = value
				Me.SendPropertyChanged("SECREATKEY")
				Me.OnSECREATKEYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ALAMATWEB", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property ALAMATWEB() As String
		Get
			Return Me._ALAMATWEB
		End Get
		Set
			If (String.Equals(Me._ALAMATWEB, value) = false) Then
				Me.OnALAMATWEBChanging(value)
				Me.SendPropertyChanging
				Me._ALAMATWEB = value
				Me.SendPropertyChanged("ALAMATWEB")
				Me.OnALAMATWEBChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_REMARKS", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property REMARKS() As String
		Get
			Return Me._REMARKS
		End Get
		Set
			If (String.Equals(Me._REMARKS, value) = false) Then
				Me.OnREMARKSChanging(value)
				Me.SendPropertyChanging
				Me._REMARKS = value
				Me.SendPropertyChanged("REMARKS")
				Me.OnREMARKSChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISACTIVE", DbType:="Bit NOT NULL")>  _
	Public Property ISACTIVE() As Boolean
		Get
			Return Me._ISACTIVE
		End Get
		Set
			If ((Me._ISACTIVE = value)  _
						= false) Then
				Me.OnISACTIVEChanging(value)
				Me.SendPropertyChanging
				Me._ISACTIVE = value
				Me.SendPropertyChanged("ISACTIVE")
				Me.OnISACTIVEChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
